# Generated by Django 2.0.7 on 2019-02-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Places'},
        ),
    ]
