# Generated by Django 2.0.7 on 2019-02-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_customer_id',
            new_name='stripe_subscription_id',
        ),
    ]
