# Generated by Django 2.1.1 on 2019-01-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_location', models.IntegerField(choices=[(0, 'Restaurant'), (1, 'Bar'), (2, 'Office'), (3, 'Hotel'), (4, 'Other')], default=0, verbose_name='What type of location is it?')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
    ]
