# Generated by Django 2.1.1 on 2019-01-31 14:23

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_location', models.IntegerField(choices=[(0, 'Restaurant'), (1, 'Bar'), (2, 'Office'), (3, 'Hotel'), (4, 'Other')], default=0, verbose_name='What type of location is it?')),
                ('location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Canberra', 'Canberra')], default='', max_length=200, verbose_name='In which city is your location?')),
                ('nameofthelocation', models.CharField(default='', max_length=120, verbose_name='What is the name of the Location?')),
                ('websiteurl', models.URLField(blank='True', null='True', verbose_name='What is the Website URL?')),
                ('address', models.CharField(default='', max_length=120, verbose_name='What is the Street Address?')),
                ('seatingcapacity', models.CharField(default='', max_length=120, verbose_name='What is the seating capacity?')),
                ('thetime', models.CharField(choices=[('4:00pm', '4:00pm'), ('4:30pm', '4:30pm'), ('5:00pm', '5:00pm'), ('5:30pm', '5:30pm'), ('6:00pm', '6:00pm'), ('6:30pm', '6:30pm')], default='', max_length=200, verbose_name='At what time does dinner typically start?')),
                ('thedays', models.CharField(choices=[('7 Days a Week', '7 Days a Week'), ('Weekdays only', 'Weekdays only'), ('Weekends only', 'Weekends only'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=200, verbose_name='Which days would you like Spacious to operate in your space?')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Your First name')),
                ('lastname', models.CharField(default='', max_length=120, verbose_name='Your Last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Your Phone number')),
                ('email', models.EmailField(default='', max_length=120)),
                ('theways', multiselectfield.db.fields.MultiSelectField(choices=[('E-mail', 'E-mail'), ('Phone', 'Phone'), ('Text', 'Text')], default='', max_length=17, verbose_name="What's the best way to reach you?")),
            ],
        ),
    ]
