# Generated by Django 2.1.1 on 2019-01-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitaspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeowner',
            name='lastname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='placeowner',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='placeowner',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
