# Generated by Django 2.1.1 on 2019-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitaspace', '0002_auto_20190131_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeowner',
            name='location',
            field=models.CharField(choices=[('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Canberra', 'Canberra')], default='', max_length=200, verbose_name='In which city is your location?'),
        ),
    ]
