# Generated by Django 2.1.1 on 2019-01-31 05:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('submitaspace', '0003_placeowner_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeowner',
            name='address',
            field=models.CharField(default='', max_length=120, verbose_name='What is the Street Address?'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='nameofthelocation',
            field=models.CharField(default='', max_length=120, verbose_name='What is the name of the Location?'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Your Phone number.'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='seatingcapacity',
            field=models.CharField(default='', max_length=120, verbose_name='What is the seating capacity?'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='thedays',
            field=models.CharField(choices=[('7 Days a Week', '7 Days a Week'), ('Weekdays only', 'Weekdays only'), ('Weekends only', 'Weekends only'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=200, verbose_name='Which days would you like Spacious to operate in your space?'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='thetime',
            field=models.CharField(choices=[('4:00pm', '4:00pm'), ('4:30pm', '4:30pm'), ('5:00pm', '5:00pm'), ('5:30pm', '5:30pm'), ('6:00pm', '6:00pm'), ('6:30pm', '6:30pm')], default='', max_length=200, verbose_name='At what time does dinner typically start?'),
        ),
        migrations.AddField(
            model_name='placeowner',
            name='websiteurl',
            field=models.URLField(blank='True', null='True', verbose_name='What is the Website URL?'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='placeowner',
            name='lastname',
            field=models.CharField(default='', max_length=120, verbose_name='Your Last name'),
        ),
        migrations.AlterField(
            model_name='placeowner',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Your First name'),
        ),
    ]
