# Generated by Django 2.1.1 on 2019-01-31 05:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('submitaspace', '0004_auto_20190131_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeowner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Your Phone number'),
        ),
    ]
