# Generated by Django 2.1.1 on 2019-01-31 05:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submitaspace', '0005_auto_20190131_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeowner',
            name='theways',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('E-mail', 'E-mail'), ('Phone', 'Phone'), ('Text', 'Text')], default='', max_length=17, verbose_name="What's the best way to reach you?"),
        ),
    ]
